### ISSUE TITLE
Implement Trimming Support

### ISSUE THREAD

**Issue by dustin-lunarg** [LunarG/gfxreconstruct#185]
Currently, the capture layer will capture all frames from application start to exit.  Add support to the layer for capturing a range of frames, as well as a utility for trimming existing capture files to a sub-range of frames.

This feature will be implemented with the following sub-tasks.
- [ ] Implement State Tracking for Trimming (#182)
- [ ] Implement Trimming in the Capture Layer (#183)
- [ ] Implement a Trimming Utility (#184)

**Comment by dustin-lunarg** [comment]
The initial trimming implementation is currently available on the dev branch.
